# Generated by Django 4.2.7 on 2023-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONT_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continents', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('co2', models.FloatField()),
                ('co2_per_cap', models.FloatField()),
                ('co2_coal', models.FloatField()),
                ('co2_cons', models.FloatField()),
                ('co2_gas', models.FloatField()),
                ('co2_oil', models.FloatField()),
                ('co2_trade', models.FloatField()),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
