# Generated by Django 4.2.7 on 2023-11-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cont_y'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cont_y',
            options={},
        ),
    ]
