# Generated by Django 4.2.7 on 2023-11-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cont_y_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CONT_Y',
        ),
    ]
