# Generated by Django 4.2.7 on 2023-11-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cont_y'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CONT_Y',
        ),
    ]
